#!/usr/bin/env python3
"""Render IDEAS.md / TASKS.md / PRIORITIES.md into a self-contained dashboard.html.

No dependencies, no network, no JS. Supports the small markdown subset the
templates actually use: headings, bullets, tables, blockquotes, rules, bold,
and inline code.
"""

import argparse
import html
import os
import re
import sys
from datetime import datetime

SECTIONS = [
    ("PRIORITIES.md", "Priorities", "What to build next — generated by <code>team-collab triage</code>."),
    ("TASKS.md", "Active tasks", "Who is building what right now. Claim before you start."),
    ("IDEAS.md", "Ideas", "Append-only backlog. Anyone can add."),
]


def inline(text):
    """Escape, then re-apply the inline markdown we support."""
    out = html.escape(text)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", out)
    out = re.sub(r"(?<!_)_([^_\n]+)_(?!_)", r"<em>\1</em>", out)
    return out


def split_row(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def is_divider(line):
    return bool(re.fullmatch(r"\|[\s:|-]+\|", line.strip()))


def render(md):
    lines = md.splitlines()
    out = []
    i = 0
    list_open = False

    def close_list():
        nonlocal list_open
        if list_open:
            out.append("</ul>")
            list_open = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            close_list()
            i += 1
            continue

        # Table: a pipe row followed by a --- divider row
        if stripped.startswith("|") and i + 1 < len(lines) and is_divider(lines[i + 1]):
            close_list()
            headers = split_row(stripped)
            out.append("<div class='tablewrap'><table><thead><tr>")
            out.extend(f"<th>{inline(h)}</th>" for h in headers)
            out.append("</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = split_row(lines[i])
                if any(c for c in cells):
                    out.append("<tr>")
                    out.extend(f"<td>{inline(c)}</td>" for c in cells)
                    out.append("</tr>")
                i += 1
            out.append("</tbody></table></div>")
            continue

        if re.fullmatch(r"-{3,}|\*{3,}|_{3,}", stripped):
            close_list()
            out.append("<hr>")
            i += 1
            continue

        m = re.match(r"(#{1,6})\s+(.*)", stripped)
        if m:
            close_list()
            # Demote one level so file headings sit under the section heading.
            level = min(len(m.group(1)) + 1, 6)
            out.append(f"<h{level}>{inline(m.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith(">"):
            close_list()
            body = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                body.append(lines[i].strip().lstrip(">").strip())
                i += 1
            out.append(f"<blockquote>{inline(' '.join(body))}</blockquote>")
            continue

        m = re.match(r"[-*+]\s+(.*)", stripped)
        if m:
            if not list_open:
                out.append("<ul>")
                list_open = True
            out.append(f"<li>{inline(m.group(1))}</li>")
            i += 1
            continue

        close_list()
        out.append(f"<p>{inline(stripped)}</p>")
        i += 1

    close_list()
    return "\n".join(out)


CSS = """
:root { color-scheme: light dark; --bg:#fff; --fg:#1a1a1a; --muted:#666;
  --line:#e3e3e3; --card:#fafafa; --accent:#2b6cb0; }
@media (prefers-color-scheme: dark) { :root { --bg:#16181c; --fg:#e6e6e6;
  --muted:#9aa0a6; --line:#2c3038; --card:#1c1f24; --accent:#7cb3ee; } }
* { box-sizing: border-box; }
body { margin:0; padding:2rem 1rem 4rem; background:var(--bg); color:var(--fg);
  font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }
.wrap { max-width: 900px; margin: 0 auto; }
h1 { font-size:1.7rem; margin:0 0 .25rem; }
.sub { color:var(--muted); font-size:.9rem; margin-bottom:1.5rem; }
.note { background:var(--card); border:1px solid var(--line); border-left:3px solid var(--accent);
  border-radius:6px; padding:.85rem 1rem; font-size:.88rem; color:var(--muted); margin-bottom:2rem; }
.note code { color:var(--fg); }
section { border:1px solid var(--line); border-radius:8px; background:var(--card);
  padding:1.25rem 1.5rem; margin-bottom:1.5rem; }
section > h2 { margin:0; font-size:1.25rem; }
section > .desc { color:var(--muted); font-size:.85rem; margin:.2rem 0 1rem; }
h3 { font-size:1.05rem; margin:1.4rem 0 .4rem; }
h4 { font-size:.95rem; margin:1.1rem 0 .3rem; }
p { margin:.5rem 0; }
ul { margin:.4rem 0; padding-left:1.3rem; }
li { margin:.2rem 0; }
code { background:rgba(127,127,127,.16); padding:.12em .35em; border-radius:4px;
  font-size:.88em; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
blockquote { margin:.7rem 0; padding:.5rem .9rem; border-left:3px solid var(--accent);
  background:rgba(127,127,127,.07); color:var(--muted); border-radius:0 4px 4px 0; }
hr { border:0; border-top:1px solid var(--line); margin:1.2rem 0; }
.tablewrap { overflow-x:auto; margin:.7rem 0; }
table { border-collapse:collapse; width:100%; font-size:.9rem; }
th,td { border:1px solid var(--line); padding:.45rem .6rem; text-align:left; }
th { background:rgba(127,127,127,.1); font-weight:600; }
.missing { color:var(--muted); font-style:italic; }
footer { color:var(--muted); font-size:.8rem; text-align:center; margin-top:2rem; }
"""

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body><div class="wrap">
<h1>{title}</h1>
<div class="sub">Snapshot generated {stamp}</div>
<div class="note">
<strong>This page is a static snapshot, not a live view.</strong><br>
To see the latest: <code>git pull</code>, then reopen this file.<br>
To rebuild it from the markdown files: run <code>team-collab dashboard</code> in Claude Code.<br>
To re-rank ideas, flag conflicts, and raise questions: run <code>team-collab triage</code>.
</div>
{body}
<footer>Generated by team-collab · edit the markdown files, not this page</footer>
</div></body></html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=".", help="repo root containing the markdown files")
    ap.add_argument("--output", default=None, help="output path (default <dir>/dashboard.html)")
    ap.add_argument("--title", default=None, help="page title (default: directory name)")
    args = ap.parse_args()

    root = os.path.abspath(args.dir)
    if not os.path.isdir(root):
        sys.exit(f"error: not a directory: {root}")

    title = args.title or f"{os.path.basename(root)} — team dashboard"
    out_path = args.output or os.path.join(root, "dashboard.html")

    found = []
    body = []
    for fname, heading, desc in SECTIONS:
        path = os.path.join(root, fname)
        body.append(f"<section><h2>{html.escape(heading)}</h2>"
                    f"<div class='desc'>{desc}</div>")
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                content = fh.read().strip()
            body.append(render(content) if content
                        else f"<p class='missing'>{fname} is empty.</p>")
            found.append(fname)
        else:
            body.append(f"<p class='missing'>{fname} not found — "
                        f"run <code>team-collab init</code> to create it.</p>")
        body.append("</section>")

    page = PAGE.format(
        title=html.escape(title),
        css=CSS,
        stamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
        body="\n".join(body),
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(page)

    print(f"wrote {out_path}")
    print(f"sources: {', '.join(found) if found else 'none found'}")


if __name__ == "__main__":
    main()
