#!/usr/bin/env python3
"""Render the coordination markdown files into a single dashboard.html.

No build step and no Python dependencies. Supports the small markdown subset the
templates actually use: headings, bullets, tables, blockquotes, rules, fenced
code, bold, and inline code.

One deliberate exception to "no network": if the page contains a mermaid diagram,
it pulls the renderer from a CDN. That's a render-only library with no keys and no
backend, and it degrades cleanly — offline, the diagram source stays on the page as
readable text. Pages with no diagram get no script tag at all.
"""

import argparse
import html
import os
import re
import subprocess
import sys
from datetime import datetime


def repo_slug(root):
    """owner/name from the git origin remote, or None if not a GitHub repo."""
    try:
        url = subprocess.run(
            ["git", "-C", root, "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    m = re.search(r"github\.com[:/](.+?/.+?)(?:\.git)?$", url)
    return m.group(1) if m else None

SECTIONS = [
    ("PRIORITIES.md", "Priorities", "What to build next — generated by <code>team-collab triage</code>."),
    ("TASKS.md", "Active tasks", "Who is building what right now. Claim before you start."),
    ("IDEAS.md", "Ideas", "Append-only backlog. Anyone can add."),
    ("CONTEXT.md", "Shared understanding", "Decisions, gotchas, and how things work — what the group has learned."),
    ("JOURNAL.md", "Journal & open threads", "The running conversation — reasoning, arguments in progress, and what settled them."),
]


def inline(text):
    """Escape, then re-apply the inline markdown we support."""
    out = html.escape(text)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", out)
    out = re.sub(r"(?<!_)_([^_\n]+)_(?!_)", r"<em>\1</em>", out)
    return out


def split_row(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def is_divider(line):
    return bool(re.fullmatch(r"\|[\s:|-]+\|", line.strip()))


def render(md):
    lines = md.splitlines()
    # Drop the file's own top-level title — the section heading already says it.
    for n, ln in enumerate(lines):
        if ln.strip():
            if re.match(r"#\s+", ln.strip()):
                lines = lines[n + 1:]
            break
    out = []
    i = 0
    list_open = False

    def close_list():
        nonlocal list_open
        if list_open:
            out.append("</ul>")
            list_open = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            close_list()
            i += 1
            continue

        # Fenced code block. Mermaid gets rendered as a diagram; everything else
        # stays literal. Without this, a diagram's source spills out as garbled
        # paragraphs, and the template format examples render as instructions.
        if stripped.startswith("```"):
            close_list()
            lang = stripped[3:].strip().lower()
            i += 1
            body = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                body.append(lines[i])
                i += 1
            i += 1  # closing fence
            code = "\n".join(body)
            if lang == "mermaid":
                # The <pre> holds the source: mermaid replaces it when the script
                # loads, and it stays readable as-is when offline.
                out.append(
                    "<div class='mermaid-wrap'>"
                    f"<pre class='mermaid'>{html.escape(code)}</pre></div>"
                )
            else:
                out.append(f"<pre class='code'><code>{html.escape(code)}</code></pre>")
            continue

        # Table: a pipe row followed by a --- divider row
        if stripped.startswith("|") and i + 1 < len(lines) and is_divider(lines[i + 1]):
            close_list()
            headers = split_row(stripped)
            out.append("<div class='tablewrap'><table><thead><tr>")
            out.extend(f"<th>{inline(h)}</th>" for h in headers)
            out.append("</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = split_row(lines[i])
                if any(c for c in cells):
                    out.append("<tr>")
                    out.extend(f"<td>{inline(c)}</td>" for c in cells)
                    out.append("</tr>")
                i += 1
            out.append("</tbody></table></div>")
            continue

        if re.fullmatch(r"-{3,}|\*{3,}|_{3,}", stripped):
            close_list()
            out.append("<hr>")
            i += 1
            continue

        m = re.match(r"(#{1,6})\s+(.*)", stripped)
        if m:
            close_list()
            # Demote one level so file headings sit under the section heading.
            level = min(len(m.group(1)) + 1, 6)
            out.append(f"<h{level}>{inline(m.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith(">"):
            close_list()
            body = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                body.append(lines[i].strip().lstrip(">").strip())
                i += 1
            out.append(f"<blockquote>{inline(' '.join(body))}</blockquote>")
            continue

        m = re.match(r"[-*+]\s+(.*)", stripped)
        if m:
            if not list_open:
                out.append("<ul>")
                list_open = True
            out.append(f"<li>{inline(m.group(1))}</li>")
            i += 1
            continue

        close_list()
        out.append(f"<p>{inline(stripped)}</p>")
        i += 1

    close_list()
    return "\n".join(out)


CSS = """
:root { color-scheme: light dark; --bg:#fff; --fg:#1a1a1a; --muted:#666;
  --line:#e3e3e3; --card:#fafafa; --accent:#2b6cb0; }
@media (prefers-color-scheme: dark) { :root { --bg:#16181c; --fg:#e6e6e6;
  --muted:#9aa0a6; --line:#2c3038; --card:#1c1f24; --accent:#7cb3ee; } }
* { box-sizing: border-box; }
body { margin:0; padding:2rem 1rem 4rem; background:var(--bg); color:var(--fg);
  font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }
.wrap { max-width: 900px; margin: 0 auto; }
h1 { font-size:1.7rem; margin:0 0 .25rem; }
.sub { color:var(--muted); font-size:.9rem; margin-bottom:1.5rem; }
.note { background:var(--card); border:1px solid var(--line); border-left:3px solid var(--accent);
  border-radius:6px; padding:.85rem 1rem; font-size:.88rem; color:var(--muted); margin-bottom:2rem; }
.note code { color:var(--fg); }
table.cmds { border-collapse:collapse; width:100%; margin:.8rem 0 .6rem; font-size:.85rem; }
table.cmds td { border:0; padding:.22rem .5rem .22rem 0; vertical-align:top; }
table.cmds td:first-child { white-space:nowrap; width:1%; }
.snap { display:block; margin-top:.5rem; padding-top:.5rem; border-top:1px solid var(--line); }
.links { display:block; margin-top:.5rem; padding-top:.5rem; border-top:1px solid var(--line); }
.links a { color:var(--accent); }
section { border:1px solid var(--line); border-radius:8px; background:var(--card);
  padding:1.25rem 1.5rem; margin-bottom:1.5rem; }
section > h2 { margin:0; font-size:1.25rem; }
section > .desc { color:var(--muted); font-size:.85rem; margin:.2rem 0 1rem; }
h3 { font-size:1.05rem; margin:1.4rem 0 .4rem; }
h4 { font-size:.95rem; margin:1.1rem 0 .3rem; }
p { margin:.5rem 0; }
ul { margin:.4rem 0; padding-left:1.3rem; }
li { margin:.2rem 0; }
code { background:rgba(127,127,127,.16); padding:.12em .35em; border-radius:4px;
  font-size:.88em; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
blockquote { margin:.7rem 0; padding:.5rem .9rem; border-left:3px solid var(--accent);
  background:rgba(127,127,127,.07); color:var(--muted); border-radius:0 4px 4px 0; }
hr { border:0; border-top:1px solid var(--line); margin:1.2rem 0; }
.tablewrap { overflow-x:auto; margin:.7rem 0; }
table { border-collapse:collapse; width:100%; font-size:.9rem; }
th,td { border:1px solid var(--line); padding:.45rem .6rem; text-align:left; }
th { background:rgba(127,127,127,.1); font-weight:600; }
pre.code { background:rgba(127,127,127,.10); border:1px solid var(--line); border-radius:6px;
  padding:.7rem .9rem; overflow-x:auto; font-size:.85em; margin:.7rem 0; }
pre.code code { background:none; padding:0; }
.mermaid-wrap { margin:1rem 0; overflow-x:auto; border:1px solid var(--line);
  border-radius:6px; background:rgba(127,127,127,.05); padding:.9rem; }
/* Shown as source until mermaid loads; replaced by the rendered SVG if it does.
   Offline this stays visible and readable, which is the intended fallback. */
pre.mermaid { margin:0; font-size:.82em; white-space:pre; color:var(--muted);
  font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
pre.mermaid[data-processed] { color:inherit; }
.mermaid-wrap svg { max-width:100%; height:auto; display:block; margin:0 auto; }
.missing { color:var(--muted); font-style:italic; }
footer { color:var(--muted); font-size:.8rem; text-align:center; margin-top:2rem; }
"""

# Loaded only when the page actually contains a diagram, and only from a CDN —
# so the page stays a single self-contained file with no build step. If the CDN
# is unreachable (offline, or a locked-down network) nothing breaks: the <pre>
# already holds the diagram source and simply stays visible as text.
MERMAID_SCRIPT = """<script type="module">
try {
  const m = await import("https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs");
  const dark = matchMedia("(prefers-color-scheme: dark)").matches;
  m.default.initialize({
    startOnLoad: true,
    securityLevel: "strict",
    theme: dark ? "dark" : "default",
  });
} catch (e) {
  // Offline. The diagram source is already on the page in readable form.
}
</script>"""

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body><div class="wrap">
<h1>{title}</h1>
<div class="sub">Snapshot generated {stamp}</div>
<div class="note">
<strong>Just talk to your own Claude Code with this repo open.</strong>
Say what you mean — "I'll take the CSV export", "that's working now", "it'd be nice if…" —
and it offers to update these files for you. Nothing to memorize.
Short forms work too, if you prefer them:
<table class="cmds">
<tr><td><code>idea: dark mode for settings</code></td><td>adds it to the backlog under your name</td></tr>
<tr><td><code>triage</code></td><td>re-ranks everything, flags clashes, asks what's unclear</td></tr>
<tr><td><code>claim csv export</code></td><td>marks you as working on it, makes the branch</td></tr>
<tr><td><code>done</code></td><td>moves your task to finished</td></tr>
<tr><td><code>status</code></td><td>tells you who's on what and what's next</td></tr>
<tr><td><code>refresh</code></td><td>rebuilds this page from the latest files</td></tr>
</table>
{links}
<span class="snap">This page is a static snapshot — <code>git pull</code> and reopen it to see
other people's updates.</span>
</div>
{body}
<footer>Generated by team-collab · edit the markdown files, not this page</footer>
</div>
{mermaid_script}
</body></html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=".", help="repo root containing the markdown files")
    ap.add_argument("--output", default=None, help="output path (default <dir>/dashboard.html)")
    ap.add_argument("--title", default=None, help="page title (default: directory name)")
    args = ap.parse_args()

    root = os.path.abspath(args.dir)
    if not os.path.isdir(root):
        sys.exit(f"error: not a directory: {root}")

    title = args.title or f"{os.path.basename(root)} — team dashboard"
    out_path = args.output or os.path.join(root, "dashboard.html")

    found = []
    body = []
    for fname, heading, desc in SECTIONS:
        path = os.path.join(root, fname)
        body.append(f"<section><h2>{html.escape(heading)}</h2>"
                    f"<div class='desc'>{desc}</div>")
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                content = fh.read().strip()
            body.append(render(content) if content
                        else f"<p class='missing'>{fname} is empty.</p>")
            found.append(fname)
        else:
            body.append(f"<p class='missing'>{fname} not found — "
                        f"run <code>team-collab init</code> to create it.</p>")
        body.append("</section>")

    slug = repo_slug(root)
    if slug:
        base = f"https://github.com/{html.escape(slug)}"
        links = (
            '<span class="links"><strong>Discuss on GitHub:</strong> '
            f'<a href="{base}/issues/new?labels=idea&title=Idea%3A+">post an idea</a> · '
            f'<a href="{base}/issues?q=is%3Aissue+is%3Aopen+label%3Aidea">open ideas &amp; comments</a> · '
            f'<a href="{base}/blob/main/PRIORITIES.md">priorities</a> · '
            f'<a href="{base}/blob/main/TASKS.md">tasks</a>'
            "<br>Those pages work on your phone and follow the repo's own access rules — "
            "only collaborators can see or post.</span>"
        )
    else:
        links = (
            '<span class="links">No GitHub remote detected — add one with '
            "<code>git remote add origin ...</code> to get idea/discussion links here.</span>"
        )

    rendered_body = "\n".join(body)
    page = PAGE.format(
        title=html.escape(title),
        css=CSS,
        stamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
        body=rendered_body,
        links=links,
        # Only pull in the renderer when there's actually a diagram to draw, so
        # a page without one stays fully offline and script-free as before.
        mermaid_script=MERMAID_SCRIPT if "class='mermaid'" in rendered_body else "",
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(page)

    print(f"wrote {out_path}")
    print(f"sources: {', '.join(found) if found else 'none found'}")


if __name__ == "__main__":
    main()
